# Generated by Django 2.0.5 on 2018-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='enigma/media/profile_image/photo.jpg', upload_to='profile_image'),
        ),
    ]
