# Generated by Django 2.0.5 on 2018-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180610_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='enigma/media/profile_image/photo_fc98Hl5.jpg', upload_to='profile_image'),
        ),
    ]
