# Generated by Django 2.0.5 on 2018-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180610_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='enigma/media/profile_image/human.jpg', upload_to='profile_image'),
        ),
    ]
