# Generated by Django 2.0.5 on 2018-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180614_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='enigma/media/profile_image/80ac7d053444b25f4de44baf53ca21e7_2.jpg', upload_to='profile_image'),
        ),
    ]
