# Generated by Django 2.0.5 on 2018-06-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180614_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/profile_image/dog.jpg', upload_to='profile_image'),
        ),
    ]
